### ISSUE TITLE
发现两处问题

### ISSUE THREAD

**Issue by yue460186yu** [hoyho/WeGouSharp#5]
1、在趴多个文章的时候，在其循环中，出现数据被覆盖现象
2、在子文章中的发文时间没有被赋值
![image](https://user-images.githubusercontent.com/26730428/43569452-182dfa3e-966a-11e8-8a52-0e44771fa345.png)

**Comment by hoyho** [comment]
@yue460186yu 可否提供下公众号ID

**Comment by yue460186yu** [comment]
prdcweixin   可以从微信搜狗中获取的列表对比你的看看。

**Comment by yue460186yu** [comment]
prdcweixin

**Comment by yue460186yu** [comment]
上面截图是我改了以后的样子，说白了就是循环的时候，对象没有被new,导致list中的对象可能被重新改值的现象，因为是引用类型嘛……

**Comment by hoyho** [comment]
> 上面截图是我改了以后的样子，说白了就是循环的时候，对象没有被new,导致list中的对象可能被重新改值的现象，因为是引用类型嘛……
--


@yue460186yu 

新分支改掉这种有毛病的写法了
[https://github.com/hoyho/WeGouSharp/blob/1ff20e51da02178c609ff5de8ffdef43469bde9e/src/WeGouSharp/BLL/WechatSogouBasic.cs#L201](https://github.com/hoyho/WeGouSharp/blob/1ff20e51da02178c609ff5de8ffdef43469bde9e/src/WeGouSharp/BLL/WechatSogouBasic.cs#L201) 近期会合并到master

**Comment by yue460186yu** [comment]
还有就是你没有给子发文的发文时间赋值，上面截图有两个红框，你看下。

**Comment by hoyho** [comment]
修复完成已经合并到master
https://github.com/hoyho/WeGouSharp/blob/ae4666fa40512aa7278bd7a2ee24e8986b772067/tests/WeGouTest/MessageTest.cs#L30
