### ISSUE TITLE
Browser.cs的路径需要修改

### ISSUE THREAD

**Issue by yf2468** [hoyho/WeGouSharp#9]
else if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                geckodriverPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Resource\\geckodriver\\windows\\")
                                  + "," + "geckodriver.exe";
            }

**Comment by hoyho** [comment]
这个路径有什么问题吗？因为手头上没有Windows系统进行测试，这段代码没测试到

**Comment by hoyho** [comment]
已在虚拟机中测试，windows 10 64 位，修复默认路径 [code](https://github.com/hoyho/WeGouSharp/blob/f1b3d43b51280b13cf21443b2018180a4ffa0bc1/src/WeGouSharp/Browser.cs#L266)
